### ISSUE TITLE
_ in (=)/3 causes leakage

### ISSUE THREAD

**Issue by UWN** [SuperDisk/tar.pl#1]
Nice! One issue attracted my attention:

```
   if_( ROctalStr = [0x20 | _]
         , ROctalStr = [0x20 | ROctalStr2]
         , ROctalStr2 = ROctalStr
       ),
   ...
```

Here, the underscore causes leakage, since for Prolog this looks like a real variable. In many top levels like those of Scryer and SWI the culprit is not shown directly, but two answers are produced:

```
?- ROctalStr = [0x20], if_( ROctalStr = [0x20 | _], ROctalStr = [0x20 | ROctalStr2], ROctalStr2 = ROctalStr ).
   ROctalStr = [32], ROctalStr2 = []
;  ROctalStr = [32], ROctalStr2 = [32], unexpected.
```

To get the real full answer, use `call_residue_vars/2`:

```
?- ROctalStr = [0x20], call_residue_vars(if_( ROctalStr = [0x20 | _], ROctalStr = [0x20 | ROctalStr2], ROctalStr2 = ROctalStr ), Vars).
   ROctalStr = [32], ROctalStr2 = [], Vars = []
;  ROctalStr = [32], ROctalStr2 = [32], Vars = [_A], dif:dif([32],[32|_A]), unexpected.
```
So the `dif/2` is unanware of the fact that this variable occurs nowhere.

I believe (but did not check any further) that an empty octal string is not expected. In that case 

```
?- ROctalStr = [0x20], ROctalStr = [Ch|_], call_residue_vars(if_( Ch = 0x20, ROctalStr = [0x20 | ROctalStr2], ROctalStr2 = ROctalStr ), Vars).
   ROctalStr = [32], Ch = 32, ROctalStr2 = [], Vars = [].
```
gives exactly one efficient answer.  Otherwise you would have to special case the `[]`.

**Comment by SuperDisk** [comment]
Interesting, I wouldn't have noticed. Thanks for the suggestion, I implemented it. Let me know if you see anything else that could be improved :)
